rabbit_params:
  host: rabbit
  consume_from: yelp_reviews_funny_counter_consumer
  produce_to:
    - yelp_business_funny_reviews_count
  messages_to_group: 1000

group_aggregates:
  - name: ReviewCount
    type: Count
    args: {}

operations:
  - name: IsFunny
    type: Filter
    args:
      filter_by: funny
      keep_cond: leq_than_1
  - name: GroupByBusiness
    type: GroupBy
    args:
      group_by: business_id
      aggregates:
        - ReviewCount

message_pipeline:
  - IsFunny
  - GroupByBusiness

message_pipeline_kwargs:
  ends_to_receive: 1
  ends_to_send: 1
  data_path: /data_volume/message_pipeline
  signature: reviews_funny_counter
  commits_until_save: 30

message_set_params:
  set_data_path: /data_volume/message_set